services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - e-commerce-net
    restart: unless-stopped

  mail-dev:
    container_name: e_commerce_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - e-commerce-net

  mongodb:
    container_name: e-commerce-mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo:/data
    networks:
      - e-commerce-net

#  elasticsearch:
#    container_name: elasticsearch
#    image: elasticsearch:7.17.3
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#    networks:
#      - e-commerce-net
#
#  logstash:
#    container_name: logstash
#    image: logstash:7.17.3
#    ports:
#      - "5044:5044"
#    volumes:
#      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    networks:
#      - e-commerce-net
#
#  kibana:
#    container_name: kibana
#    image: kibana:7.17.3
#    ports:
#      - "5601:5601"
#    environment:
#      ELASTICSEARCH_HOST: http://elasticsearch:9200
#
#    networks:
#      - e-commerce-net

networks:
  e-commerce-net:
    driver: bridge

volumes:
  postgres:
  mongo: