spring:
  cloud:
    config:
      override-system-properties: false
eureka:
  client:
    service-url:
      defaultZone: https://discovery-service-qfs9.onrender.com
logging:
  config: classpath:logback-spring.xml