spring:
  datasource:
    url: ${databaseUrl}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: ${bootStrapServers}
    security:
      protocol: SASL_SSL
    sasl:
      mechanism: PLAIN
      jaas:
        config: ${jaasConfig}
      #      bootstrap-servers: localhost:9092


  mail:
    host: smtp.mailersend.net
#    host: localhost
    port: 587
    access_token: ${mailAccessToken}
    from_mail: noreply@test-ywj2lpndeqqg7oqz.mlsender.net
    username: ${mailUsername}
    password: ${mailPassword}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

security:
  jwt:
    secret-key: ${jwtSecretKey}
    expiration-time: 7200000
server:
  port: 8010