spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: lb:http://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
#          filters:
#            - AuthenticationFilter

        - id: auth-service-user
          uri: lb:http://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/user/**

        - id: product-catalog
          uri: lb:http://PRODUCT-CATALOG
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: shopping-cart-service
          uri: lb:http://SHOPPING-CART-SERVICE
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
          filters:
            - AuthenticationFilter

        - id: chat-service
          uri: lb:http://CHAT-SERVICE
          predicates:
            - Path=/api/v1/chat/**
server:
  port: 8222

security:
  jwt:
    secret-key: ${jwtSecretKey}