spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092

  mail:
    host: localhost
    port: 1025
    username: juma
    password: juma
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8050