spring:
  data:
    mongodb:
      username: mongo
      password: mongo
      host: localhost
      port: 27017
      database: orders
      authentication-database: admin

server:
  port: 8040

application:
  config:
    shopping-cart-url: http://localhost:8222/api/v1/cart
    product-url: http://localhost:8222/api/v1/products
