server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce-payments
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    function:
      definition: paymentProcessor;paymentSupplier
    stream:
      bindings:
        paymentProcessor-in-0:
          destination: order-event
        paymentSupplier-out-0:
          destination: payment-event

#  cloud:
#    stream:
#      function:
#        definition: paymentProcessor;paymentSupplier
#      bindings:
#        paymentProcessor-in-0:
#          destination: order-event
#        paymentProcessor-out-0:
#          destination: payment-event
mpesa:
  daraja:
    consumer-key: ${consumerKey}
    consumer-secret: ${consumerSecret}
    grant-type: client_credentials
    callback-url: https://b725547b860b.ngrok-free.app/api/v1/payment/transaction-result
    short-code: 174379
    passkey: ${passKey}
