spring:
  data:
    mongodb:
      username: mongo
      password: mongo
      host: localhost
      port: 27017
      database: product_catalog
      authentication-database: admin

server:
  port: 8020